local _, ns = ...

---------------------------------------------------------------------------
-- Trainer advice data (generated October 5, 2026 from Codex's private research draft,
-- planning/TRAINER_SPELLS_DRAFT.lua; original judgements, no copied guide text). Per
-- class token and English spell name: c = everyone / spec / nice / skip, t = the trees
-- it is a priority for (Classic order, left to right in Forever's one tree), r = why,
-- k = a condition, ok = seen at a trainer in Forever. Training.lua reads it.
---------------------------------------------------------------------------
ns.TRAINER_ADVICE = {
  DRUID = {
    ["Abolish Poison"] = { c = "everyone", r = "Remove harmful effects without needing to be the party healer." },
    ["Aquatic Form"] = { c = "everyone", r = "Learn the form for travel, escape or emergency durability regardless of tree." },
    ["Barkskin"] = { c = "everyone", r = "A defensive or resource tool helps every route." },
    ["Bash"] = { c = "everyone", r = "Control a dangerous pull before healing or escaping." },
    ["Bear Form"] = { c = "everyone", r = "Learn the form for travel, escape or emergency durability regardless of tree." },
    ["Berserk"] = { c = "spec", t = { "Feral Combat" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Cat Form"] = { c = "everyone", r = "Learn the form for travel, escape or emergency durability regardless of tree." },
    ["Challenging Roar"] = { c = "spec", t = { "Feral Combat" }, r = "Learn for bear tanking or emergency threat control.", k = "Any tree tanking dungeons needs bear tools; tree labels do not forbid off-spec tanking." },
    ["Claw"] = { c = "spec", t = { "Feral Combat" }, r = "Buy the attacks used in your bear or cat rotation." },
    ["Cower"] = { c = "skip", r = "Threat reduction has little solo value; revisit if cat damage pulls group aggro." },
    ["Cure Poison"] = { c = "everyone", r = "Remove harmful effects without needing to be the party healer." },
    ["Dash"] = { c = "everyone", r = "Travel and escape save repeated journeys and deaths." },
    ["Demoralizing Roar"] = { c = "spec", t = { "Feral Combat" }, r = "Keep defensive bear tools useful when tanking or making heavy pulls." },
    ["Dire Bear Form"] = { c = "everyone", r = "Learn the form for travel, escape or emergency durability regardless of tree." },
    ["Enrage"] = { c = "spec", t = { "Feral Combat" }, r = "Learn for bear tanking or emergency threat control.", k = "Any tree tanking dungeons needs bear tools; tree labels do not forbid off-spec tanking." },
    ["Entangling Roots"] = { c = "everyone", r = "Control a dangerous pull before healing or escaping." },
    ["Faerie Fire"] = { c = "everyone", r = "Armour reduction helps physical attacks; learn for form play too." },
    ["Faerie Fire (Feral)"] = { c = "spec", t = { "Feral Combat" }, r = "Legacy name only: reconcile with Forever trainer data before showing advice." },
    ["Feline Grace"] = { c = "everyone", r = "Travel and escape save repeated journeys and deaths." },
    ["Feral Charge"] = { c = "spec", t = { "Feral Combat" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Ferocious Bite"] = { c = "spec", t = { "Feral Combat" }, r = "Buy the attacks used in your bear or cat rotation." },
    ["Frenzied Regeneration"] = { c = "spec", t = { "Feral Combat" }, r = "Keep defensive bear tools useful when tanking or making heavy pulls." },
    ["Gift of the Wild"] = { c = "nice", r = "Group convenience can wait; single-target buffs cover small parties." },
    ["Growl"] = { c = "spec", t = { "Feral Combat" }, r = "Learn for bear tanking or emergency threat control.", k = "Any tree tanking dungeons needs bear tools; tree labels do not forbid off-spec tanking." },
    ["Healing Touch"] = { c = "everyone", r = "Keep an effective heal even when levelling in animal forms." },
    ["Hibernate"] = { c = "nice", r = "Useful control for the right enemy type." },
    ["Hurricane"] = { c = "spec", t = { "Balance" }, r = "Buy for deliberate caster area pulls; mana and positioning matter." },
    ["Innervate"] = { c = "everyone", r = "A defensive or resource tool helps every route." },
    ["Insect Swarm"] = { c = "spec", t = { "Balance" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Lacerate"] = { c = "spec", t = { "Feral Combat" }, r = "Buy the attacks used in your bear or cat rotation.", k = "Any tree tanking dungeons needs bear tools; tree labels do not forbid off-spec tanking." },
    ["Mark of the Wild"] = { c = "everyone", r = "A useful self and party buff for every route." },
    ["Maul"] = { c = "spec", t = { "Feral Combat" }, r = "Buy the attacks used in your bear or cat rotation.", k = "Any tree tanking dungeons needs bear tools; tree labels do not forbid off-spec tanking." },
    ["Moonfire"] = { c = "spec", t = { "Balance" }, r = "Keep caster attacks current if used; early Wrath and Moonfire help everyone before forms.", k = "Early caster damage is needed before forms; later ranks depend on caster play." },
    ["Moonkin Form"] = { c = "spec", t = { "Balance" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Nature's Grasp"] = { c = "everyone", r = "Control a dangerous pull before healing or escaping." },
    ["Nature's Swiftness"] = { c = "spec", t = { "Restoration" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Omen of Clarity"] = { c = "everyone", r = "A defensive or resource tool helps every route." },
    ["Pounce"] = { c = "spec", t = { "Feral Combat" }, r = "Buy for stealth openers or attacks from behind; solo face-to-face fights use other attacks." },
    ["Primal Bite"] = { c = "spec", t = { "Feral Combat" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Prowl"] = { c = "everyone", r = "Travel and escape save repeated journeys and deaths." },
    ["Rake"] = { c = "spec", t = { "Feral Combat" }, r = "Buy the attacks used in your bear or cat rotation." },
    ["Ravage"] = { c = "spec", t = { "Feral Combat" }, r = "Buy for stealth openers or attacks from behind; solo face-to-face fights use other attacks." },
    ["Rebirth"] = { c = "everyone", r = "Resurrection is useful in groups even for damage builds." },
    ["Regrowth"] = { c = "spec", t = { "Restoration" }, r = "Upgrade for dungeon healing; damage builds can keep a usable heal and defer surplus ranks.", k = "Any tree regularly healing groups needs suitable heals; Restoration is the default priority context." },
    ["Rejuvenation"] = { c = "spec", t = { "Restoration" }, r = "Upgrade for dungeon healing; damage builds can keep a usable heal and defer surplus ranks.", k = "Any tree regularly healing groups needs suitable heals; Restoration is the default priority context." },
    ["Remove Curse"] = { c = "everyone", r = "Remove harmful effects without needing to be the party healer." },
    ["Revive"] = { c = "everyone", r = "Resurrection is useful in groups even for damage builds." },
    ["Rip"] = { c = "spec", t = { "Feral Combat" }, r = "Buy the attacks used in your bear or cat rotation." },
    ["Shifting Power"] = { c = "spec", t = { "Feral Combat" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Shred"] = { c = "spec", t = { "Feral Combat" }, r = "Buy for stealth openers or attacks from behind; solo face-to-face fights use other attacks." },
    ["Soothe Animal"] = { c = "skip", r = "Narrow pull avoidance can wait on a tight training budget." },
    ["Starfire"] = { c = "spec", t = { "Balance" }, r = "Keep caster attacks current if used; early Wrath and Moonfire help everyone before forms." },
    ["Swiftmend"] = { c = "spec", t = { "Restoration" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Swipe"] = { c = "spec", t = { "Feral Combat" }, r = "Buy the attacks used in your bear or cat rotation.", k = "Any tree tanking dungeons needs bear tools; tree labels do not forbid off-spec tanking." },
    ["Teleport: Moonglade"] = { c = "everyone", r = "Travel and escape save repeated journeys and deaths." },
    ["Thorns"] = { c = "nice", r = "Reflective damage helps melee pulls; direct attacks come first." },
    ["Tiger's Fury"] = { c = "spec", t = { "Feral Combat" }, r = "Legacy name only: reconcile with Forever trainer data before showing advice." },
    ["Track Humanoids"] = { c = "nice", r = "Tracking helps find humanoid quest targets." },
    ["Tranquility"] = { c = "spec", t = { "Restoration" }, r = "Upgrade for dungeon healing; damage builds can keep a usable heal and defer surplus ranks.", k = "Any tree regularly healing groups needs suitable heals; Restoration is the default priority context." },
    ["Travel Form"] = { c = "everyone", r = "Learn the form for travel, escape or emergency durability regardless of tree." },
    ["Wild Growth"] = { c = "spec", t = { "Restoration" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Wrath"] = { c = "spec", t = { "Balance" }, r = "Keep caster attacks current if used; early Wrath and Moonfire help everyone before forms.", k = "Early caster damage is needed before forms; later ranks depend on caster play." },
  },
  HUNTER = {
    ["Aimed Shot"] = { c = "spec", t = { "Beast Mastery", "Marksmanship" }, r = "Keep the ranged package current for ranged levelling; melee builds can defer later ranks." },
    ["Arcane Shot"] = { c = "spec", t = { "Beast Mastery", "Marksmanship" }, r = "Keep the ranged package current for ranged levelling; melee builds can defer later ranks." },
    ["Aspect of the Beast"] = { c = "spec", t = { "Survival" }, r = "Keep current when deliberately levelling in melee." },
    ["Aspect of the Cheetah"] = { c = "everyone", r = "Movement and emergency control matter in every tree." },
    ["Aspect of the Hawk"] = { c = "spec", t = { "Beast Mastery", "Marksmanship" }, r = "Keep the ranged package current for ranged levelling; melee builds can defer later ranks." },
    ["Aspect of the Monkey"] = { c = "nice", r = "Defence helps when enemies reach you; a damage aspect usually serves ranged pulls." },
    ["Aspect of the Pack"] = { c = "nice", r = "Group travel is useful; turn it off before anyone takes damage." },
    ["Aspect of the Wild"] = { c = "nice", r = "Defensive support for specific enemies; buy when the route needs it." },
    ["Auto Shot"] = { c = "everyone", r = "Your basic ranged attack must be available." },
    ["Beast Lore"] = { c = "nice", r = "Pet selection and scouting are convenient; combat basics come first." },
    ["Beast Training"] = { c = "everyone", r = "Pet ownership and upkeep are central tools for every tree." },
    ["Bestial Wrath"] = { c = "spec", t = { "Beast Mastery" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Black Arrow"] = { c = "spec", t = { "Marksmanship", "Beast Mastery" }, r = "Useful ranged damage or area attacks; avoid breaking control." },
    ["Call Pet"] = { c = "everyone", r = "Pet ownership and upkeep are central tools for every tree." },
    ["Concussive Shot"] = { c = "everyone", r = "Movement and emergency control matter in every tree." },
    ["Counterattack"] = { c = "spec", t = { "Survival" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Deterrence"] = { c = "spec", t = { "Survival" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Disengage"] = { c = "nice", r = "Situational threat or control helps particular group pulls." },
    ["Dismiss Pet"] = { c = "everyone", r = "Pet ownership and upkeep are central tools for every tree." },
    ["Distracting Shot"] = { c = "nice", r = "Situational threat or control helps particular group pulls." },
    ["Eagle Eye"] = { c = "nice", r = "Pet selection and scouting are convenient; combat basics come first." },
    ["Explosive Trap"] = { c = "nice", r = "Fire traps help planned pulls; they are not mandatory in every rotation." },
    ["Eyes of the Beast"] = { c = "nice", r = "Pet selection and scouting are convenient; combat basics come first." },
    ["Feed Pet"] = { c = "everyone", r = "Pet ownership and upkeep are central tools for every tree." },
    ["Feign Death"] = { c = "everyone", r = "Movement and emergency control matter in every tree." },
    ["Flare"] = { c = "nice", r = "Pet selection and scouting are convenient; combat basics come first." },
    ["Freezing Trap"] = { c = "everyone", r = "Movement and emergency control matter in every tree." },
    ["Frost Trap"] = { c = "everyone", r = "Movement and emergency control matter in every tree." },
    ["Hunter's Mark"] = { c = "everyone", r = "Mark targets you fight when making ranged attacks." },
    ["Immolation Trap"] = { c = "nice", r = "Fire traps help planned pulls; they are not mandatory in every rotation." },
    ["Intimidation"] = { c = "spec", t = { "Beast Mastery" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Lacerate"] = { c = "spec", t = { "Survival" }, r = "Keep current when deliberately levelling in melee." },
    ["Mail"] = { c = "nice", r = "Train when using the corresponding gear or passive; confirm exact service name." },
    ["Mend Pet"] = { c = "everyone", r = "Keep healing adequate for the pet doing your pulls." },
    ["Mongoose Bite"] = { c = "spec", t = { "Survival" }, r = "Keep current when deliberately levelling in melee." },
    ["Multi-Shot"] = { c = "spec", t = { "Marksmanship", "Beast Mastery" }, r = "Useful ranged damage or area attacks; avoid breaking control." },
    ["Rapid Fire"] = { c = "everyone", r = "A damage cooldown helps difficult pulls." },
    ["Raptor Strike"] = { c = "spec", t = { "Survival" }, r = "Keep current when deliberately levelling in melee.", k = "Useful early before a pet and a ranged rotation; later ranks follow melee use." },
    ["Revive Pet"] = { c = "everyone", r = "Pet ownership and upkeep are central tools for every tree." },
    ["Scare Beast"] = { c = "nice", r = "Situational threat or control helps particular group pulls." },
    ["Scatter Shot"] = { c = "spec", t = { "Marksmanship" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Scorpid Sting"] = { c = "nice", r = "Defensive support for specific enemies; buy when the route needs it." },
    ["Serpent Sting"] = { c = "spec", t = { "Beast Mastery", "Marksmanship" }, r = "Keep the ranged package current for ranged levelling; melee builds can defer later ranks." },
    ["Sniper Shot"] = { c = "spec", t = { "Marksmanship" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Strider Kick"] = { c = "spec", t = { "Survival" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Summon Hawk"] = { c = "spec", t = { "Beast Mastery" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Tame Beast"] = { c = "everyone", r = "Pet ownership and upkeep are central tools for every tree." },
    ["Track Beasts"] = { c = "nice", r = "Tracking saves searching time but does not improve every fight." },
    ["Track Demons"] = { c = "nice", r = "Tracking saves searching time but does not improve every fight." },
    ["Track Dragonkin"] = { c = "nice", r = "Tracking saves searching time but does not improve every fight." },
    ["Track Elementals"] = { c = "nice", r = "Tracking saves searching time but does not improve every fight." },
    ["Track Giants"] = { c = "nice", r = "Tracking saves searching time but does not improve every fight." },
    ["Track Hidden"] = { c = "nice", r = "Tracking saves searching time but does not improve every fight." },
    ["Track Humanoids"] = { c = "nice", r = "Tracking saves searching time but does not improve every fight." },
    ["Track Undead"] = { c = "nice", r = "Tracking saves searching time but does not improve every fight." },
    ["Tranquilizing Shot"] = { c = "nice", r = "Endgame utility rather than an ordinary levelling purchase." },
    ["Trueshot Aura"] = { c = "spec", t = { "Marksmanship" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Viper Sting"] = { c = "skip", r = "Mana pressure seldom solves ordinary quest pulls; reconsider for player combat." },
    ["Volley"] = { c = "spec", t = { "Marksmanship", "Beast Mastery" }, r = "Useful ranged damage or area attacks; avoid breaking control." },
    ["Wing Clip"] = { c = "everyone", r = "Movement and emergency control matter in every tree." },
  },
  MAGE = {
    ["Amplify Magic"] = { c = "skip", r = "Situational magic adjustments are poor priorities on a limited levelling budget.", ok = true },
    ["Arcane Blast"] = { c = "spec", t = { "Arcane" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play.", ok = true },
    ["Arcane Brilliance"] = { c = "nice", r = "The single-target intellect buff already covers a small party." },
    ["Arcane Explosion"] = { c = "spec", t = { "Arcane", "Frost" }, r = "A close-range area attack for Arcane damage and Frost levelling pulls controlled with Frost Nova.", k = "Useful for planned multiple-enemy pulls, including Frost Nova plus Arcane Explosion from about level 22. Upgrade while using this method; single-target routes can defer unused ranks.", ok = true },
    ["Arcane Intellect"] = { c = "everyone", r = "Keep your self buff, drinking and food useful at your level.", ok = true },
    ["Arcane Missiles"] = { c = "spec", t = { "Arcane" }, r = "A channelled single-target attack for an Arcane route; keep it current while it is part of your rotation.", k = "This is a single-target option. Defer unused ranks if another attack replaces it.", ok = true },
    ["Arcane Power"] = { c = "spec", t = { "Arcane" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Blast Wave"] = { c = "spec", t = { "Fire" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play.", ok = true },
    ["Blink"] = { c = "everyone", r = "Control, interruption, cleansing and escape matter in every tree." },
    ["Blizzard"] = { c = "spec", t = { "Frost" }, r = "Buy for frost control or planned area pulls.", k = "Area-pull playstyle can justify this in other trees; do not recommend AoE pulls solely from the category.", ok = true },
    ["Cold Snap"] = { c = "spec", t = { "Frost" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Combustion"] = { c = "spec", t = { "Fire" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Comprehend Scroll"] = { c = "nice", r = "Optional scroll and library tools come after combat essentials." },
    ["Cone of Cold"] = { c = "spec", t = { "Frost" }, r = "Buy for frost control or planned area pulls.", ok = true },
    ["Conjure Food"] = { c = "everyone", r = "Keep your self buff, drinking and food useful at your level.", ok = true },
    ["Conjure Mana Agate"] = { c = "nice", r = "An optional emergency mana reserve for long or difficult pulls; drinking covers ordinary solo downtime.", k = "Learn the gem you expect to use. New gem tiers need not be bought solely to maintain every older option.", ok = true },
    ["Conjure Mana Citrine"] = { c = "nice", r = "An optional emergency mana reserve for long or difficult pulls; drinking covers ordinary solo downtime.", k = "Learn the gem you expect to use. New gem tiers need not be bought solely to maintain every older option.", ok = true },
    ["Conjure Mana Jade"] = { c = "nice", r = "An optional emergency mana reserve for long or difficult pulls; drinking covers ordinary solo downtime.", k = "Learn the gem you expect to use. New gem tiers need not be bought solely to maintain every older option.", ok = true },
    ["Conjure Mana Ruby"] = { c = "nice", r = "An optional emergency mana reserve for long or difficult pulls; drinking covers ordinary solo downtime.", k = "Learn the gem you expect to use. New gem tiers need not be bought solely to maintain every older option.", ok = true },
    ["Conjure Water"] = { c = "everyone", r = "Keep your self buff, drinking and food useful at your level.", ok = true },
    ["Counterspell"] = { c = "everyone", r = "Control, interruption, cleansing and escape matter in every tree.", ok = true },
    ["Dampen Magic"] = { c = "skip", r = "Situational magic adjustments are poor priorities on a limited levelling budget.", ok = true },
    ["Detect Magic"] = { c = "skip", r = "Legacy name only: reconcile with Forever trainer data before showing advice." },
    ["Evocation"] = { c = "everyone", r = "Mana recovery helps every school." },
    ["Fire Blast"] = { c = "everyone", r = "An instant finisher helps every levelling route end a fight while moving or before another cast completes.", k = "Upgrade while using it to finish targets; its Fire school is not a Fire-tree learning or recommendation restriction.", ok = true },
    ["Fire Ward"] = { c = "nice", r = "Buy a matching ward when the zone needs it; every rank is not essential.", ok = true },
    ["Fireball"] = { c = "spec", t = { "Fire" }, r = "Keep used fire attacks current; early Fireball serves everyone before talent choices.", k = "Early ranks are essential until another main attack replaces it; later unused fire ranks may wait.", ok = true },
    ["Flamestrike"] = { c = "spec", t = { "Fire" }, r = "Buy when your fire route uses area pulls.", k = "Area-pull playstyle can justify this in other trees; do not recommend AoE pulls solely from the category.", ok = true },
    ["Frost Armor"] = { c = "everyone", r = "A defensive armour for early levelling in every tree; later Ice Armor replaces it.", k = "Keep one armour active. Do not buy obsolete Frost Armor ranks after replacing it with a suitable later armour.", ok = true },
    ["Frost Nova"] = { c = "everyone", r = "Control, interruption, cleansing and escape matter in every tree.", ok = true },
    ["Frost Ward"] = { c = "nice", r = "Buy a matching ward when the zone needs it; every rank is not essential.", ok = true },
    ["Frostbolt"] = { c = "spec", t = { "Frost" }, r = "Keep current for frost damage; other trees can retain an early rank for the slow.", k = "Learn an early slow in every tree; upgrade damage ranks when frost is your main attack.", ok = true },
    ["Frostfire Bolt"] = { c = "spec", t = { "Fire", "Frost" }, r = "Consider for a matching caster build after testing its rotation; new does not automatically mean better.", ok = true },
    ["Ice Armor"] = { c = "everyone", r = "A defensive armour option for every tree when enemies reach you.", k = "Keep one armour active; this replaces Frost Armor rather than stacking with it. Use Mage Armor instead when its mana recovery better suits the route.", ok = true },
    ["Ice Barrier"] = { c = "spec", t = { "Frost" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play.", ok = true },
    ["Ice Block"] = { c = "spec", t = { "Frost" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Ice Lance"] = { c = "spec", t = { "Frost" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play.", ok = true },
    ["Mage Armor"] = { c = "nice", r = "An optional mana-recovery armour for later caster levelling; choose it when reduced downtime is more useful than the defensive armour.", k = "Keep one armour active. Frost Armor or Ice Armor remains a useful defensive choice; maintaining every alternative rank is optional.", ok = true },
    ["Mana Shield"] = { c = "nice", r = "Emergency protection costs mana; use for survival rather than routine damage.", ok = true },
    ["Polymorph"] = { c = "everyone", r = "Control, interruption, cleansing and escape matter in every tree.", ok = true },
    ["Polymorph: Cow"] = { c = "nice", r = "An appearance alternative to normal Polymorph; not needed for stronger levelling control." },
    ["Polymorph: Pig"] = { c = "nice", r = "An appearance alternative to normal Polymorph; not needed for stronger levelling control." },
    ["Polymorph: Turtle"] = { c = "nice", r = "An appearance alternative to normal Polymorph; not needed for stronger levelling control." },
    ["Portal: Darnassus"] = { c = "nice", r = "Group transport saves or earns gold but is not required for solo questing." },
    ["Portal: Ironforge"] = { c = "nice", r = "Group transport saves or earns gold but is not required for solo questing." },
    ["Portal: Orgrimmar"] = { c = "nice", r = "Group transport saves or earns gold but is not required for solo questing." },
    ["Portal: Stormwind"] = { c = "nice", r = "Group transport saves or earns gold but is not required for solo questing." },
    ["Portal: Thunder Bluff"] = { c = "nice", r = "Group transport saves or earns gold but is not required for solo questing." },
    ["Portal: Undercity"] = { c = "nice", r = "Group transport saves or earns gold but is not required for solo questing." },
    ["Presence of Mind"] = { c = "spec", t = { "Arcane" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Pyroblast"] = { c = "spec", t = { "Fire" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play.", ok = true },
    ["Remove Lesser Curse"] = { c = "everyone", r = "Control, interruption, cleansing and escape matter in every tree." },
    ["Scorch"] = { c = "spec", t = { "Fire" }, r = "Keep used fire attacks current; early Fireball serves everyone before talent choices.", ok = true },
    ["Slow Fall"] = { c = "everyone", r = "Control, interruption, cleansing and escape matter in every tree." },
    ["Study"] = { c = "nice", r = "Optional scroll and library tools come after combat essentials." },
    ["Teleport: Dalaran"] = { c = "nice", r = "Train destinations you visit; every city need not be bought at once." },
    ["Teleport: Darnassus"] = { c = "nice", r = "Train destinations you visit; every city need not be bought at once." },
    ["Teleport: Ironforge"] = { c = "nice", r = "Train destinations you visit; every city need not be bought at once." },
    ["Teleport: Orgrimmar"] = { c = "nice", r = "Train destinations you visit; every city need not be bought at once." },
    ["Teleport: Stormwind"] = { c = "nice", r = "Train destinations you visit; every city need not be bought at once." },
    ["Teleport: Thunder Bluff"] = { c = "nice", r = "Train destinations you visit; every city need not be bought at once." },
    ["Teleport: Undercity"] = { c = "nice", r = "Train destinations you visit; every city need not be bought at once." },
  },
  PALADIN = {
    ["Blessing of Freedom"] = { c = "everyone", r = "Emergency survival and control help every tree." },
    ["Blessing of Kings"] = { c = "everyone", r = "Melee, mana and stat buffs support questing and groups." },
    ["Blessing of Light"] = { c = "spec", t = { "Holy" }, r = "Buy when healing regularly or casting under pressure." },
    ["Blessing of Might"] = { c = "everyone", r = "Melee, mana and stat buffs support questing and groups." },
    ["Blessing of Protection"] = { c = "everyone", r = "Emergency survival and control help every tree." },
    ["Blessing of Sacrifice"] = { c = "nice", r = "Useful group support; ordinary solo questing has no recipient or need." },
    ["Blessing of Salvation"] = { c = "nice", r = "Useful group support; ordinary solo questing has no recipient or need." },
    ["Blessing of Sanctuary"] = { c = "spec", t = { "Protection" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Blessing of Wisdom"] = { c = "everyone", r = "Melee, mana and stat buffs support questing and groups." },
    ["Cleanse"] = { c = "everyone", r = "Cleansing and resurrection are class utility, not healer-only purchases." },
    ["Concentration Aura"] = { c = "spec", t = { "Holy" }, r = "Buy when healing regularly or casting under pressure." },
    ["Consecration"] = { c = "spec", t = { "Protection", "Retribution" }, r = "Buy for planned multiple-enemy fights; single-target questing can defer extra ranks." },
    ["Devotion Aura"] = { c = "nice", r = "Use a suitable passive aura; every unused aura rank need not be maintained." },
    ["Divine Favor"] = { c = "spec", t = { "Holy" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Divine Intervention"] = { c = "skip", r = "A coordinated wipe tool can wait until organised group content." },
    ["Divine Protection"] = { c = "everyone", r = "Emergency survival and control help every tree." },
    ["Divine Shield"] = { c = "everyone", r = "Emergency survival and control help every tree." },
    ["Exorcism"] = { c = "nice", r = "Buy on undead or demon-heavy routes; these are not attacks against every target." },
    ["Fire Resistance Aura"] = { c = "nice", r = "Buy matching resistance when the zone or party needs it." },
    ["Flash of Light"] = { c = "everyone", r = "Keep a reliable self heal and a fast emergency heal." },
    ["Frost Resistance Aura"] = { c = "nice", r = "Buy matching resistance when the zone or party needs it." },
    ["Greater Blessing of Kings"] = { c = "nice", r = "High-level group convenience; ordinary blessings remain sufficient." },
    ["Greater Blessing of Light"] = { c = "nice", r = "High-level group convenience; ordinary blessings remain sufficient." },
    ["Greater Blessing of Might"] = { c = "nice", r = "High-level group convenience; ordinary blessings remain sufficient." },
    ["Greater Blessing of Salvation"] = { c = "nice", r = "High-level group convenience; ordinary blessings remain sufficient." },
    ["Greater Blessing of Sanctuary"] = { c = "spec", t = { "Protection" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Greater Blessing of Wisdom"] = { c = "nice", r = "High-level group convenience; ordinary blessings remain sufficient." },
    ["Hammer of Justice"] = { c = "everyone", r = "Emergency survival and control help every tree." },
    ["Hammer of Wrath"] = { c = "everyone", r = "A finishing attack shortens dangerous end-of-fight time." },
    ["Hammer of the Righteous"] = { c = "spec", t = { "Protection" }, r = "Buy for tanking; solo damage does not need every threat and shield tool." },
    ["Holy Light"] = { c = "everyone", r = "Keep a reliable self heal and a fast emergency heal." },
    ["Holy Shield"] = { c = "spec", t = { "Protection" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Holy Shock"] = { c = "spec", t = { "Holy" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Holy Strike"] = { c = "spec", t = { "Retribution" }, r = "A direct melee attack is a priority for a damage route." },
    ["Holy Wrath"] = { c = "nice", r = "Buy on undead or demon-heavy routes; these are not attacks against every target." },
    ["Judgement"] = { c = "everyone", r = "Judgement enables your seals regardless of tree." },
    ["Lay on Hands"] = { c = "everyone", r = "Emergency survival and control help every tree." },
    ["Light's Vigil"] = { c = "spec", t = { "Holy" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Plate Mail"] = { c = "nice", r = "Train when using the corresponding gear or passive; confirm exact service name." },
    ["Purify"] = { c = "everyone", r = "Cleansing and resurrection are class utility, not healer-only purchases." },
    ["Redemption"] = { c = "everyone", r = "Cleansing and resurrection are class utility, not healer-only purchases." },
    ["Repentance"] = { c = "spec", t = { "Retribution" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Retribution Aura"] = { c = "nice", r = "Use a suitable passive aura; every unused aura rank need not be maintained." },
    ["Righteous Fury"] = { c = "spec", t = { "Protection" }, r = "Buy for tanking; solo damage does not need every threat and shield tool." },
    ["Seal of Command"] = { c = "spec", t = { "Retribution" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Seal of Fury"] = { c = "spec", t = { "Protection" }, r = "Buy for tanking; solo damage does not need every threat and shield tool." },
    ["Seal of Justice"] = { c = "nice", r = "Useful to stop runners rather than as a mandatory damage seal." },
    ["Seal of Light"] = { c = "nice", r = "Sustain options suit long fights; compare against your normal damage seal." },
    ["Seal of Righteousness"] = { c = "everyone", r = "A broadly useful damage seal; defer surplus ranks after a chosen alternative replaces it." },
    ["Seal of Wisdom"] = { c = "nice", r = "Sustain options suit long fights; compare against your normal damage seal." },
    ["Seal of the Crusader"] = { c = "spec", t = { "Retribution" }, r = "Use when it fits your seal and judgement rotation." },
    ["Sense Undead"] = { c = "skip", r = "Minimap detection can wait while gold is needed for combat tools." },
    ["Shadow Resistance Aura"] = { c = "nice", r = "Buy matching resistance when the zone or party needs it." },
    ["Summon Charger"] = { c = "nice", r = "An eventual travel upgrade rather than an early spell purchase." },
    ["Summon Warhorse"] = { c = "everyone", r = "Take the class mount route; confirm riding and acquisition requirements." },
    ["Swift Judgement"] = { c = "spec", t = { "Retribution" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Templar's Bulwark"] = { c = "spec", t = { "Protection" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Turn Undead"] = { c = "nice", r = "Control can rescue an undead pull; avoid bringing friends with fleeing enemies." },
    ["Voice of Truth"] = { c = "spec", t = { "Holy" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
  },
  PRIEST = {
    ["Abolish Disease"] = { c = "everyone", r = "Cleansing, resurrection and fear protection help every tree." },
    ["Binding Heal"] = { c = "spec", t = { "Holy" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Chastise"] = { c = "nice", r = "Racial damage or mitigation helps when it fits your actual fights." },
    ["Confounding Flash"] = { c = "everyone", r = "A racial survival or mana recovery tool is valuable when your race can learn it." },
    ["Contingency Plan"] = { c = "everyone", r = "A racial survival or mana recovery tool is valuable when your race can learn it." },
    ["Cure Disease"] = { c = "everyone", r = "Cleansing, resurrection and fear protection help every tree." },
    ["Dark Sacrifice"] = { c = "everyone", r = "A racial survival or mana recovery tool is valuable when your race can learn it." },
    ["Desperate Prayer"] = { c = "everyone", r = "A racial survival or mana recovery tool is valuable when your race can learn it." },
    ["Devouring Plague"] = { c = "spec", t = { "Shadow" }, r = "Upgrade regularly used shadow attacks; other builds can defer unused ranks." },
    ["Dispel Magic"] = { c = "everyone", r = "Cleansing, resurrection and fear protection help every tree." },
    ["Divine Grace"] = { c = "nice", r = "An ally rescue helps groups but does not replace your own emergency heal." },
    ["Divine Spirit"] = { c = "everyone", r = "A baseline spirit buff supports every route." },
    ["Elune's Grace"] = { c = "everyone", r = "A racial survival or mana recovery tool is valuable when your race can learn it." },
    ["Fade"] = { c = "nice", r = "Group threat management is useful; solo use does not erase a fight." },
    ["Fear Ward"] = { c = "everyone", r = "Cleansing, resurrection and fear protection help every tree." },
    ["Feedback"] = { c = "skip", r = "Narrow reactive caster pressure can wait during ordinary questing." },
    ["Flash Heal"] = { c = "everyone", r = "Keep an emergency heal even when levelling as damage." },
    ["Greater Heal"] = { c = "everyone", r = "Keep one effective main heal current; later heal families supersede early ones." },
    ["Heal"] = { c = "everyone", r = "Keep one effective main heal current; later heal families supersede early ones." },
    ["Hex of Weakness"] = { c = "nice", r = "Racial damage or mitigation helps when it fits your actual fights." },
    ["Holy Fire"] = { c = "spec", t = { "Holy", "Discipline" }, r = "Keep current for a holy-damage route; early Smite helps before any tree is chosen." },
    ["Holy Nova"] = { c = "spec", t = { "Holy" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Inner Fire"] = { c = "everyone", r = "Keep defensive buffs and your absorb useful at your level." },
    ["Inner Focus"] = { c = "spec", t = { "Discipline" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Lesser Heal"] = { c = "everyone", r = "Keep one effective main heal current; later heal families supersede early ones." },
    ["Levitate"] = { c = "nice", r = "Situational control and traversal can avoid dangerous fights." },
    ["Lightwell"] = { c = "spec", t = { "Holy" }, r = "Optional group healing if available; do not assume it can be bought in Forever." },
    ["Mana Burn"] = { c = "skip", r = "Mana pressure is mainly a player-combat tool, not a routine quest kill plan." },
    ["Mind Blast"] = { c = "spec", t = { "Shadow" }, r = "Upgrade regularly used shadow attacks; other builds can defer unused ranks." },
    ["Mind Control"] = { c = "nice", r = "Situational control and traversal can avoid dangerous fights." },
    ["Mind Flay"] = { c = "spec", t = { "Shadow" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Mind Soothe"] = { c = "nice", r = "Situational control and traversal can avoid dangerous fights." },
    ["Mind Vision"] = { c = "skip", r = "Scouting can wait on a tight training budget." },
    ["Penance"] = { c = "spec", t = { "Discipline" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Power Infusion"] = { c = "spec", t = { "Discipline" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Power Word: Fortitude"] = { c = "everyone", r = "Keep defensive buffs and your absorb useful at your level." },
    ["Power Word: Shield"] = { c = "everyone", r = "Keep defensive buffs and your absorb useful at your level." },
    ["Prayer of Fortitude"] = { c = "nice", r = "Group convenience can wait; single-target buffs cover small parties." },
    ["Prayer of Healing"] = { c = "spec", t = { "Holy", "Discipline" }, r = "Upgrade these additional heals when regularly healing parties." },
    ["Prayer of Mending"] = { c = "spec", t = { "Holy" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Prayer of Shadow Protection"] = { c = "nice", r = "Group convenience can wait; single-target buffs cover small parties." },
    ["Prayer of Spirit"] = { c = "nice", r = "Group convenience can wait; single-target buffs cover small parties." },
    ["Psychic Scream"] = { c = "everyone", r = "A fear escape can save a bad pull; fleeing targets may bring friends." },
    ["Renew"] = { c = "spec", t = { "Holy", "Discipline" }, r = "Upgrade these additional heals when regularly healing parties." },
    ["Resurrection"] = { c = "everyone", r = "Cleansing, resurrection and fear protection help every tree." },
    ["Shackle Undead"] = { c = "nice", r = "Situational control and traversal can avoid dangerous fights." },
    ["Shadow Protection"] = { c = "nice", r = "Buy for shadow-heavy zones or parties." },
    ["Shadow Word: Death"] = { c = "spec", t = { "Shadow" }, r = "Upgrade regularly used shadow attacks; other builds can defer unused ranks." },
    ["Shadow Word: Pain"] = { c = "everyone", r = "Useful early damage for every tree; keep current while actively using it." },
    ["Shadowform"] = { c = "spec", t = { "Shadow" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Shadowguard"] = { c = "nice", r = "Racial damage or mitigation helps when it fits your actual fights." },
    ["Silence"] = { c = "spec", t = { "Shadow" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Smite"] = { c = "spec", t = { "Holy", "Discipline" }, r = "Keep current for a holy-damage route; early Smite helps before any tree is chosen.", k = "Early main attack for every tree; later ranks depend on a holy-damage route." },
    ["Starshards"] = { c = "nice", r = "Racial damage or mitigation helps when it fits your actual fights." },
    ["Touch of Weakness"] = { c = "nice", r = "Racial damage or mitigation helps when it fits your actual fights." },
    ["Vampiric Embrace"] = { c = "spec", t = { "Shadow" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
  },
  ROGUE = {
    ["Adrenaline Rush"] = { c = "spec", t = { "Combat" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Ambush"] = { c = "spec", t = { "Assassination", "Subtlety", "Combat" }, r = "Buy for daggers and attacks from behind; a sword solo route does not need these ranks." },
    ["Backstab"] = { c = "spec", t = { "Assassination", "Subtlety", "Combat" }, r = "Buy for daggers and attacks from behind; a sword solo route does not need these ranks." },
    ["Blade Flurry"] = { c = "spec", t = { "Combat" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Blind"] = { c = "everyone", r = "Control, interruption and escape are useful in every tree." },
    ["Cheap Shot"] = { c = "everyone", r = "Control, interruption and escape are useful in every tree." },
    ["Cold Blood"] = { c = "spec", t = { "Assassination" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Crippling Poison"] = { c = "nice", r = "A slow helps runners and player combat; choose for the route." },
    ["Crippling Poison II"] = { c = "nice", r = "A slow helps runners and player combat; choose for the route." },
    ["Deadly Poison"] = { c = "nice", r = "A sustained-fight poison alternative; short pulls or control can favour instant damage." },
    ["Deadly Poison II"] = { c = "nice", r = "A sustained-fight poison alternative; short pulls or control can favour instant damage." },
    ["Deadly Poison III"] = { c = "nice", r = "A sustained-fight poison alternative; short pulls or control can favour instant damage." },
    ["Deadly Poison IV"] = { c = "nice", r = "A sustained-fight poison alternative; short pulls or control can favour instant damage." },
    ["Deadly Poison V"] = { c = "nice", r = "A sustained-fight poison alternative; short pulls or control can favour instant damage." },
    ["Detect Traps"] = { c = "nice", r = "Utility helps travel or loot opportunities; combat essentials come first." },
    ["Disarm Trap"] = { c = "nice", r = "Utility helps travel or loot opportunities; combat essentials come first." },
    ["Distract"] = { c = "everyone", r = "Control, interruption and escape are useful in every tree." },
    ["Dual Wield"] = { c = "everyone", r = "Both hands are central to rogue combat." },
    ["Evasion"] = { c = "everyone", r = "Control, interruption and escape are useful in every tree." },
    ["Eviscerate"] = { c = "everyone", r = "Keep a general combo builder and damage finisher useful." },
    ["Expose Armor"] = { c = "skip", r = "Short solo targets often die before armour reduction pays back; revisit for sustained group fights." },
    ["Feint"] = { c = "nice", r = "Useful in groups where you pull threat; not a solo escape." },
    ["Garrote"] = { c = "spec", t = { "Assassination", "Subtlety" }, r = "Bleeds suit longer fights or a bleed route; defer if enemies die quickly." },
    ["Ghostly Strike"] = { c = "spec", t = { "Subtlety" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Gouge"] = { c = "everyone", r = "Control, interruption and escape are useful in every tree." },
    ["Hemorrhage"] = { c = "spec", t = { "Subtlety" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Instant Poison"] = { c = "everyone", r = "A basic damage poison is useful once poison use is unlocked." },
    ["Instant Poison II"] = { c = "everyone", r = "A basic damage poison is useful once poison use is unlocked." },
    ["Instant Poison III"] = { c = "everyone", r = "A basic damage poison is useful once poison use is unlocked." },
    ["Instant Poison IV"] = { c = "everyone", r = "A basic damage poison is useful once poison use is unlocked." },
    ["Instant Poison V"] = { c = "everyone", r = "A basic damage poison is useful once poison use is unlocked." },
    ["Instant Poison VI"] = { c = "everyone", r = "A basic damage poison is useful once poison use is unlocked." },
    ["Kick"] = { c = "everyone", r = "Control, interruption and escape are useful in every tree." },
    ["Kidney Shot"] = { c = "everyone", r = "Control, interruption and escape are useful in every tree." },
    ["Mind-numbing Poison"] = { c = "skip", r = "Caster or healing pressure poisons can wait unless player combat is part of the route." },
    ["Mind-numbing Poison II"] = { c = "skip", r = "Caster or healing pressure poisons can wait unless player combat is part of the route." },
    ["Mind-numbing Poison III"] = { c = "skip", r = "Caster or healing pressure poisons can wait unless player combat is part of the route." },
    ["Mutilate"] = { c = "spec", t = { "Assassination" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Parry"] = { c = "nice", r = "Train when using the corresponding gear or passive; confirm exact service name." },
    ["Pick Lock"] = { c = "nice", r = "Utility helps travel or loot opportunities; combat essentials come first." },
    ["Pick Pocket"] = { c = "nice", r = "Utility helps travel or loot opportunities; combat essentials come first." },
    ["Poisons"] = { c = "everyone", r = "Unlock poison use; confirm trainer versus quest acquisition." },
    ["Premeditation"] = { c = "spec", t = { "Subtlety" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Preparation"] = { c = "spec", t = { "Subtlety" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Riposte"] = { c = "spec", t = { "Combat" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Rupture"] = { c = "spec", t = { "Assassination", "Subtlety" }, r = "Bleeds suit longer fights or a bleed route; defer if enemies die quickly." },
    ["Safe Fall"] = { c = "nice", r = "Utility helps travel or loot opportunities; combat essentials come first." },
    ["Sap"] = { c = "everyone", r = "Control, interruption and escape are useful in every tree." },
    ["Sinister Strike"] = { c = "everyone", r = "Keep a general combo builder and damage finisher useful.", k = "A dagger or talent builder can replace this later; do not require unused ranks." },
    ["Slice and Dice"] = { c = "everyone", r = "Melee speed helps sustained fights; short pulls may die before it pays off." },
    ["Sprint"] = { c = "everyone", r = "Control, interruption and escape are useful in every tree." },
    ["Stealth"] = { c = "everyone", r = "Control, interruption and escape are useful in every tree." },
    ["Vanish"] = { c = "everyone", r = "Control, interruption and escape are useful in every tree." },
    ["Venom"] = { c = "spec", t = { "Assassination" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Wound Poison"] = { c = "skip", r = "Caster or healing pressure poisons can wait unless player combat is part of the route." },
    ["Wound Poison II"] = { c = "skip", r = "Caster or healing pressure poisons can wait unless player combat is part of the route." },
    ["Wound Poison III"] = { c = "skip", r = "Caster or healing pressure poisons can wait unless player combat is part of the route." },
    ["Wound Poison IV"] = { c = "skip", r = "Caster or healing pressure poisons can wait unless player combat is part of the route." },
  },
  SHAMAN = {
    ["Ancestral Spirit"] = { c = "everyone", r = "Cleansing, resurrection and offensive dispelling are not healer-only tools." },
    ["Astral Recall"] = { c = "everyone", r = "Control, fear removal and travel help every tree." },
    ["Call of the Ancestors"] = { c = "nice", r = "Extra presets and relocation help frequent totem users; basics come first." },
    ["Call of the Elements"] = { c = "everyone", r = "Recall prevents abandoned totems; a preset eases routine deployment." },
    ["Call of the Spirits"] = { c = "nice", r = "Extra presets and relocation help frequent totem users; basics come first." },
    ["Chain Heal"] = { c = "spec", t = { "Restoration" }, r = "Upgrade group healing and mana support when regularly healing dungeons.", k = "Any tree regularly healing groups needs suitable support; Restoration is the default priority context." },
    ["Chain Lightning"] = { c = "spec", t = { "Elemental" }, r = "Keep caster attacks current; early Lightning Bolt also helps melee routes pull." },
    ["Cure Disease"] = { c = "everyone", r = "Cleansing, resurrection and offensive dispelling are not healer-only tools." },
    ["Cure Poison"] = { c = "everyone", r = "Cleansing, resurrection and offensive dispelling are not healer-only tools." },
    ["Disease Cleansing Totem"] = { c = "nice", r = "Party cleansing helps repeated effects; direct cures handle occasional cases." },
    ["Dual Wield"] = { c = "nice", r = "Train when using the corresponding gear or passive; confirm exact service name." },
    ["Earth Shock"] = { c = "everyone", r = "Keep an interrupt available; extra ranks depend on using its damage." },
    ["Earthbind Totem"] = { c = "everyone", r = "Control, fear removal and travel help every tree." },
    ["Elemental Mastery"] = { c = "spec", t = { "Elemental" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Far Sight"] = { c = "skip", r = "Scouting conveniences can wait on a combat training budget." },
    ["Fire Nova"] = { c = "spec", t = { "Elemental", "Enhancement" }, r = "Damage totems help when they last through a pull; area choices need planned multi-enemy fights." },
    ["Fire Nova Totem"] = { c = "spec", t = { "Elemental", "Enhancement" }, r = "Legacy name only: reconcile with Forever trainer data before showing advice." },
    ["Fire Resistance Totem"] = { c = "nice", r = "Buy matching resistance when the zone or party needs it." },
    ["Flame Shock"] = { c = "spec", t = { "Elemental" }, r = "Keep caster attacks current; early Lightning Bolt also helps melee routes pull." },
    ["Flametongue Totem"] = { c = "nice", r = "Group fire imbue helps when no better applicable alternative is used." },
    ["Flametongue Weapon"] = { c = "spec", t = { "Enhancement" }, r = "Use a suitable imbue; early Rockbiter helps everyone but unused alternatives need not be maintained." },
    ["Frost Resistance Totem"] = { c = "nice", r = "Buy matching resistance when the zone or party needs it." },
    ["Frost Shock"] = { c = "nice", r = "A slow helps kiting or runners; buy later ranks when using damage too." },
    ["Frostbrand Weapon"] = { c = "nice", r = "A slowing imbue is situational; your normal damage imbue usually takes priority." },
    ["Ghost Wolf"] = { c = "everyone", r = "Control, fear removal and travel help every tree." },
    ["Grace of Air Totem"] = { c = "spec", t = { "Enhancement" }, r = "Melee buffs support your fights and melee groups." },
    ["Grounding Totem"] = { c = "nice", r = "Spell interception helps caster pulls or player combat." },
    ["Healing Stream Totem"] = { c = "spec", t = { "Restoration" }, r = "Upgrade group healing and mana support when regularly healing dungeons.", k = "Any tree regularly healing groups needs suitable support; Restoration is the default priority context." },
    ["Healing Wave"] = { c = "everyone", r = "Keep a main heal and a fast emergency heal useful." },
    ["Lava Burst"] = { c = "spec", t = { "Elemental" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Lesser Healing Wave"] = { c = "everyone", r = "Keep a main heal and a fast emergency heal useful." },
    ["Lightning Bolt"] = { c = "spec", t = { "Elemental" }, r = "Keep caster attacks current; early Lightning Bolt also helps melee routes pull.", k = "Early ranks support every route before specialising; later ranks follow actual use." },
    ["Lightning Shield"] = { c = "everyone", r = "A damage shield helps questing; compare against your build alternative." },
    ["Magma Totem"] = { c = "spec", t = { "Elemental", "Enhancement" }, r = "Damage totems help when they last through a pull; area choices need planned multi-enemy fights." },
    ["Mail"] = { c = "nice", r = "Train when using the corresponding gear or passive; confirm exact service name." },
    ["Mana Spring Totem"] = { c = "spec", t = { "Restoration" }, r = "Upgrade group healing and mana support when regularly healing dungeons.", k = "Any tree regularly healing groups needs suitable support; Restoration is the default priority context." },
    ["Mana Tide Totem"] = { c = "spec", t = { "Restoration" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Nature Resistance Totem"] = { c = "nice", r = "Buy matching resistance when the zone or party needs it." },
    ["Nature's Swiftness"] = { c = "spec", t = { "Restoration" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Poison Cleansing Totem"] = { c = "nice", r = "Party cleansing helps repeated effects; direct cures handle occasional cases." },
    ["Purge"] = { c = "everyone", r = "Cleansing, resurrection and offensive dispelling are not healer-only tools." },
    ["Rage of the Farseer"] = { c = "spec", t = { "Enhancement" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Reincarnation"] = { c = "everyone", r = "Cleansing, resurrection and offensive dispelling are not healer-only tools." },
    ["Riptide"] = { c = "spec", t = { "Restoration" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Rockbiter Weapon"] = { c = "spec", t = { "Enhancement" }, r = "Use a suitable imbue; early Rockbiter helps everyone but unused alternatives need not be maintained.", k = "Early ranks support every route before specialising; later ranks follow actual use." },
    ["Searing Totem"] = { c = "spec", t = { "Elemental", "Enhancement" }, r = "Damage totems help when they last through a pull; area choices need planned multi-enemy fights." },
    ["Sentry Totem"] = { c = "skip", r = "Scouting conveniences can wait on a combat training budget." },
    ["Stoneclaw Totem"] = { c = "nice", r = "Defence and distraction suit particular pulls; do not upgrade undeployed totems." },
    ["Stoneskin Totem"] = { c = "nice", r = "Defence and distraction suit particular pulls; do not upgrade undeployed totems." },
    ["Stormstrike"] = { c = "spec", t = { "Enhancement" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Strength of Earth Totem"] = { c = "spec", t = { "Enhancement" }, r = "Melee buffs support your fights and melee groups." },
    ["Totemic Projection"] = { c = "nice", r = "Extra presets and relocation help frequent totem users; basics come first." },
    ["Totemic Recall"] = { c = "everyone", r = "Recall prevents abandoned totems; a preset eases routine deployment." },
    ["Tranquil Air Totem"] = { c = "nice", r = "Group threat support is useful for some damage parties, not ordinary solo pulls." },
    ["Tremor Totem"] = { c = "everyone", r = "Control, fear removal and travel help every tree." },
    ["Two-Handed Axes and Maces"] = { c = "nice", r = "Train when using the corresponding gear or passive; confirm exact service name." },
    ["Water Breathing"] = { c = "nice", r = "Water travel saves some journeys; not every route needs it." },
    ["Water Shield"] = { c = "spec", t = { "Restoration" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Water Walking"] = { c = "nice", r = "Water travel saves some journeys; not every route needs it." },
    ["Windfury Totem"] = { c = "spec", t = { "Enhancement" }, r = "Melee buffs support your fights and melee groups." },
    ["Windfury Weapon"] = { c = "spec", t = { "Enhancement" }, r = "Use a suitable imbue; early Rockbiter helps everyone but unused alternatives need not be maintained." },
    ["Windwall Totem"] = { c = "nice", r = "Defence and distraction suit particular pulls; do not upgrade undeployed totems." },
  },
  WARLOCK = {
    ["Amplify Curse"] = { c = "spec", t = { "Affliction" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Bane of Agony"] = { c = "everyone", r = "Keep your main shadow damage current while used." },
    ["Bane of Doom"] = { c = "skip", r = "A long-delay high-level attack is not needed on ordinary levelling pulls." },
    ["Bane of Havoc"] = { c = "spec", t = { "Destruction" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Banish"] = { c = "everyone", r = "Control and emergency recovery rescue dangerous pulls." },
    ["Conflagrate"] = { c = "spec", t = { "Destruction" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Corruption"] = { c = "everyone", r = "Keep your main shadow damage current while used." },
    ["Create Firestone"] = { c = "spec", t = { "Destruction" }, r = "Upgrade used fire attacks and their supporting buff." },
    ["Create Healthstone"] = { c = "everyone", r = "Personal recovery and resurrection insurance help every tree." },
    ["Create Soulstone"] = { c = "everyone", r = "Personal recovery and resurrection insurance help every tree." },
    ["Create Spellstone"] = { c = "everyone", r = "The revised stone supports a shadow route; reassess old Classic skip habits." },
    ["Curse of Agony"] = { c = "everyone", r = "Legacy name only: reconcile with Forever trainer data before showing advice." },
    ["Curse of Doom"] = { c = "skip", r = "Legacy name only: reconcile with Forever trainer data before showing advice." },
    ["Curse of Exhaustion"] = { c = "spec", t = { "Affliction" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Curse of Recklessness"] = { c = "nice", r = "Use a curse that solves the pull; not every rank is needed for solo damage." },
    ["Curse of Shadow"] = { c = "nice", r = "Legacy name only: reconcile with Forever trainer data before showing advice." },
    ["Curse of Tongues"] = { c = "nice", r = "Use a curse that solves the pull; not every rank is needed for solo damage." },
    ["Curse of Weakness"] = { c = "nice", r = "Use a curse that solves the pull; not every rank is needed for solo damage." },
    ["Curse of the Elements"] = { c = "nice", r = "Use a curse that solves the pull; not every rank is needed for solo damage." },
    ["Death Coil"] = { c = "everyone", r = "Control and emergency recovery rescue dangerous pulls." },
    ["Demon Armor"] = { c = "everyone", r = "Use a current defence buff; Demon Armor eventually replaces Demon Skin." },
    ["Demon Skin"] = { c = "everyone", r = "Use a current defence buff; Demon Armor eventually replaces Demon Skin." },
    ["Demonic Sacrifice"] = { c = "spec", t = { "Demonology" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Detect Greater Invisibility"] = { c = "skip", r = "Scouting and hidden-target detection can wait unless a quest or player combat needs them." },
    ["Detect Invisibility"] = { c = "skip", r = "Scouting and hidden-target detection can wait unless a quest or player combat needs them." },
    ["Detect Lesser Invisibility"] = { c = "skip", r = "Scouting and hidden-target detection can wait unless a quest or player combat needs them." },
    ["Drain Life"] = { c = "everyone", r = "Keep resource recovery, self healing and shard collection useful." },
    ["Drain Mana"] = { c = "skip", r = "Draining ordinary enemies is rarely a better plan than killing them." },
    ["Drain Soul"] = { c = "everyone", r = "Keep resource recovery, self healing and shard collection useful." },
    ["Enslave Demon"] = { c = "nice", r = "Legacy name only: reconcile with Forever trainer data before showing advice." },
    ["Eye of Kilrogg"] = { c = "skip", r = "Scouting and hidden-target detection can wait unless a quest or player combat needs them." },
    ["Fear"] = { c = "everyone", r = "Control and emergency recovery rescue dangerous pulls." },
    ["Fel Domination"] = { c = "spec", t = { "Demonology" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Health Funnel"] = { c = "everyone", r = "Keep pet healing adequate for your active demon." },
    ["Hellfire"] = { c = "spec", t = { "Destruction" }, r = "Area attacks suit deliberate group pulls; life costs and threat require care." },
    ["Howl of Terror"] = { c = "nice", r = "A second fear helps emergencies; fleeing enemies can bring extra pulls." },
    ["Immolate"] = { c = "spec", t = { "Destruction" }, r = "Upgrade used fire attacks and their supporting buff." },
    ["Incinerate"] = { c = "spec", t = { "Destruction" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Inferno"] = { c = "skip", r = "Special demon rituals can wait until their group or endgame use matters." },
    ["Life Tap"] = { c = "everyone", r = "Keep resource recovery, self healing and shard collection useful." },
    ["Portal of Summoning"] = { c = "nice", r = "Group summoning helps parties rather than every solo pull." },
    ["Rain of Fire"] = { c = "spec", t = { "Destruction" }, r = "Area attacks suit deliberate group pulls; life costs and threat require care." },
    ["Ritual of Doom"] = { c = "skip", r = "Special demon rituals can wait until their group or endgame use matters." },
    ["Ritual of Summoning"] = { c = "nice", r = "Group summoning helps parties rather than every solo pull." },
    ["Searing Pain"] = { c = "nice", r = "A quick high-threat attack is situational; avoid when the pet must hold enemies." },
    ["Sense Demons"] = { c = "skip", r = "Scouting and hidden-target detection can wait unless a quest or player combat needs them." },
    ["Shadow Bolt"] = { c = "everyone", r = "Keep your main shadow damage current while used." },
    ["Shadow Ward"] = { c = "nice", r = "A matching ward helps shadow-heavy areas." },
    ["Shadowburn"] = { c = "spec", t = { "Destruction" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Siphon Life"] = { c = "spec", t = { "Affliction" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Soul Link"] = { c = "spec", t = { "Demonology" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Subjugate Demon"] = { c = "nice", r = "Water breathing and demon control suit particular quests." },
    ["Summon Dreadsteed"] = { c = "nice", r = "An eventual travel upgrade rather than early spell training." },
    ["Summon Felhunter"] = { c = "nice", r = "Alternative pets suit particular damage, control or caster fights." },
    ["Summon Felsteed"] = { c = "everyone", r = "Take the class mount route; confirm acquisition and riding requirements." },
    ["Summon Imp"] = { c = "everyone", r = "Get a working first pet and a tank option." },
    ["Summon Incubus"] = { c = "nice", r = "Alternative pets suit particular damage, control or caster fights." },
    ["Summon Succubus"] = { c = "nice", r = "Alternative pets suit particular damage, control or caster fights." },
    ["Summon Voidwalker"] = { c = "everyone", r = "Get a working first pet and a tank option." },
    ["Unending Breath"] = { c = "nice", r = "Water breathing and demon control suit particular quests." },
    ["Wrack"] = { c = "spec", t = { "Affliction" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
  },
  WARRIOR = {
    ["Battle Shout"] = { c = "everyone", r = "Keep your self and party attack buff current." },
    ["Battle Stance"] = { c = "everyone", r = "Stances and transitions support movement, interruption and defence in every tree." },
    ["Berserker Rage"] = { c = "everyone", r = "Engage, interrupt, slow and escape tools matter in every tree." },
    ["Berserker Stance"] = { c = "everyone", r = "Stances and transitions support movement, interruption and defence in every tree." },
    ["Bloodrage"] = { c = "everyone", r = "Learn cooldowns for hard fights and understand their risks and equipment requirements." },
    ["Bloodthirst"] = { c = "spec", t = { "Fury" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Challenging Shout"] = { c = "spec", t = { "Protection" }, r = "Learn for tanking or party rescue; damage trees can still tank levelling dungeons.", k = "Any tree tanking dungeons needs tank tools; tree labels do not forbid off-spec tanking." },
    ["Charge"] = { c = "everyone", r = "Engage, interrupt, slow and escape tools matter in every tree." },
    ["Cleave"] = { c = "spec", t = { "Arms", "Fury" }, r = "Multi-target attacks help planned paired or group pulls." },
    ["Concussion Blow"] = { c = "spec", t = { "Protection" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Death Wish"] = { c = "spec", t = { "Fury" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Defensive Stance"] = { c = "everyone", r = "Stances and transitions support movement, interruption and defence in every tree." },
    ["Demoralizing Shout"] = { c = "spec", t = { "Protection" }, r = "Upgrade tank threat and defence; damage routes can retain basic utility ranks.", k = "Any tree tanking dungeons needs tank tools; tree labels do not forbid off-spec tanking." },
    ["Disarm"] = { c = "nice", r = "Useful against dangerous weapon users; many creatures cannot be disarmed." },
    ["Dual Wield"] = { c = "nice", r = "Train when using the corresponding gear or passive; confirm exact service name." },
    ["Execute"] = { c = "everyone", r = "Keep reactive and finishing attacks useful when available." },
    ["Hamstring"] = { c = "everyone", r = "Engage, interrupt, slow and escape tools matter in every tree." },
    ["Heroic Strike"] = { c = "everyone", r = "Useful early and with spare rage; do not starve higher-priority attacks." },
    ["Intercept"] = { c = "everyone", r = "Engage, interrupt, slow and escape tools matter in every tree." },
    ["Intimidating Shout"] = { c = "everyone", r = "Engage, interrupt, slow and escape tools matter in every tree." },
    ["Last Stand"] = { c = "spec", t = { "Protection" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Mocking Blow"] = { c = "spec", t = { "Protection" }, r = "Learn for tanking or party rescue; damage trees can still tank levelling dungeons.", k = "Any tree tanking dungeons needs tank tools; tree labels do not forbid off-spec tanking." },
    ["Mortal Strike"] = { c = "spec", t = { "Arms" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Overpower"] = { c = "everyone", r = "Keep reactive and finishing attacks useful when available." },
    ["Parry"] = { c = "nice", r = "Train when using the corresponding gear or passive; confirm exact service name." },
    ["Piercing Howl"] = { c = "spec", t = { "Fury" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Plate Mail"] = { c = "nice", r = "Train when using the corresponding gear or passive; confirm exact service name." },
    ["Pummel"] = { c = "everyone", r = "Engage, interrupt, slow and escape tools matter in every tree." },
    ["Recklessness"] = { c = "everyone", r = "Learn cooldowns for hard fights and understand their risks and equipment requirements." },
    ["Rend"] = { c = "spec", t = { "Arms" }, r = "A bleed suits some arms routes; revised scaling makes a blanket high-level skip inappropriate." },
    ["Retaliation"] = { c = "everyone", r = "Learn cooldowns for hard fights and understand their risks and equipment requirements." },
    ["Revenge"] = { c = "spec", t = { "Protection" }, r = "Upgrade tank threat and defence; damage routes can retain basic utility ranks.", k = "Any tree tanking dungeons needs tank tools; tree labels do not forbid off-spec tanking." },
    ["Shield Bash"] = { c = "everyone", r = "Engage, interrupt, slow and escape tools matter in every tree." },
    ["Shield Block"] = { c = "spec", t = { "Protection" }, r = "Learn for tanking or party rescue; damage trees can still tank levelling dungeons.", k = "Any tree tanking dungeons needs tank tools; tree labels do not forbid off-spec tanking." },
    ["Shield Slam"] = { c = "spec", t = { "Protection" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Shield Wall"] = { c = "everyone", r = "Learn cooldowns for hard fights and understand their risks and equipment requirements." },
    ["Slam"] = { c = "spec", t = { "Arms", "Fury" }, r = "Buy when your rage and weapon rotation uses it." },
    ["Spearing Strike"] = { c = "spec", t = { "Arms" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Sunder Armor"] = { c = "spec", t = { "Protection" }, r = "Upgrade tank threat and defence; damage routes can retain basic utility ranks.", k = "Any tree tanking dungeons needs tank tools; tree labels do not forbid off-spec tanking." },
    ["Sweeping Strikes"] = { c = "spec", t = { "Arms" }, r = "Use in the matching talent build. If a trainer offers an upgrade, buy when this ability is part of your play." },
    ["Tactical Mastery"] = { c = "everyone", r = "Stances and transitions support movement, interruption and defence in every tree." },
    ["Taunt"] = { c = "spec", t = { "Protection" }, r = "Learn for tanking or party rescue; damage trees can still tank levelling dungeons.", k = "Any tree tanking dungeons needs tank tools; tree labels do not forbid off-spec tanking." },
    ["Thunder Clap"] = { c = "spec", t = { "Protection" }, r = "Upgrade tank threat and defence; damage routes can retain basic utility ranks.", k = "Any tree tanking dungeons needs tank tools; tree labels do not forbid off-spec tanking." },
    ["Victory Rush"] = { c = "everyone", r = "Keep reactive and finishing attacks useful when available." },
    ["Whirlwind"] = { c = "spec", t = { "Arms", "Fury" }, r = "Multi-target attacks help planned paired or group pulls." },
  },
}

