# Builds ClassicRecipes.lua: where each Tailoring, Enchanting, Cooking, First Aid and
# Fishing recipe came from in original Classic (vendor, boss or world drop, quest).
# Source: wow-classic-items by nexus-devs (MIT licence),
# https://github.com/nexus-devs/wow-classic-items
# Run from the repo root:  powershell -File tools\build-classic-data.ps1

$ErrorActionPreference = "Stop"
$base = "https://raw.githubusercontent.com/nexus-devs/wow-classic-items/master/data/json"
$tmp = Join-Path $env:TEMP "fl-classic-data"
New-Item -ItemType Directory -Force $tmp | Out-Null
Invoke-WebRequest "$base/data.json" -OutFile "$tmp\items.json"
Invoke-WebRequest "$base/zones.json" -OutFile "$tmp\zones.json"

$items = Get-Content "$tmp\items.json" -Raw -Encoding UTF8 | ConvertFrom-Json
$zones = @{}
$laterZones = @{}   # zones from later expansions (above level 60)
foreach ($z in (Get-Content "$tmp\zones.json" -Raw -Encoding UTF8 | ConvertFrom-Json)) {
  $zones[[int]$z.id] = $z.name
  if ($z.level -and $z.level[1] -gt 60) { $laterZones[[int]$z.id] = $true }
}
# Burning Crusade recipes numbered among the Classic ones.
function IsLater($id) { ($id -ge 21892 -and $id -le 21919) -or ($id -ge 22530 -and $id -le 22565) -or $id -eq 22647 }

$profs = "Tailoring", "Enchanting", "Cooking", "First Aid", "Fishing"
$prefix = '^(Formula|Pattern|Recipe|Manual|Plans|Schematic):\s*'

function Q([string]$s) { '"' + ($s -replace '\\', '\\' -replace '"', '\"') + '"' }

$lines = New-Object System.Collections.Generic.List[string]
# Classic items only (the list also has later expansions).
$recipes = $items | Where-Object { $_.class -eq "Recipe" -and $profs -contains $_.subclass -and $_.itemId -lt 24000 -and $_.source -and $_.name -match $prefix -and -not (IsLater $_.itemId) -and -not ($_.source.zone -and $laterZones[[int]$_.source.zone]) } | Sort-Object name
foreach ($r in $recipes) {
  $s = $r.source
  $name = ($r.name -replace $prefix, "").ToLower()
  $f = @("item = $($r.itemId)")
  switch ($s.category) {
    "Vendor" {
      $f += 'kind = "vendor"'
      if ($s.name) { $f += "npc = $(Q $s.name)" }
      if ($s.faction) { $f += "faction = $(Q $s.faction)" }
      if ($s.cost) { $f += "cost = $($s.cost)" }
    }
    "Boss Drop" {
      # Any named creature: bosses and ordinary dungeon or world mobs.
      $f += 'kind = "mob"'
      if ($s.name) { $f += "npc = $(Q $s.name)" }
    }
    "Quest" {
      $f += 'kind = "quest"'
      $q = $s.quests | Select-Object -First 1
      if ($q) { $f += "quest = $(Q $q.name)"; if ($q.faction) { $f += "faction = $(Q $q.faction)" } }
    }
    default { $f += 'kind = "drop"' }
  }
  if ($s.zone -and $zones.ContainsKey([int]$s.zone)) { $f += "zone = $(Q $zones[[int]$s.zone])" }
  if ($s.dropChance) { $f += "chance = $([math]::Round([double]$s.dropChance, 4).ToString([Globalization.CultureInfo]::InvariantCulture))" }
  $lines.Add("  [$(Q $name)] = { $($f -join ', ') },")
}

$out = @(
  "local _, ns = ...",
  "",
  "-- Where recipes came from in original Classic, for the Recipes tab. Unconfirmed in",
  "-- Forever until seen in game. Generated by tools/build-classic-data.ps1 from",
  "-- wow-classic-items by nexus-devs (MIT licence). Don't edit by hand; rerun the script.",
  "-- kind: vendor (npc, faction, cost), mob (npc, zone), drop (zone or none), quest (quest, faction).",
  "-- chance = drop chance (0.05 = 5%).",
  "ns.CLASSIC_RECIPES = {"
) + $lines + @("}")
[IO.File]::WriteAllLines((Join-Path (Get-Location) "ClassicRecipes.lua"), $out, (New-Object Text.UTF8Encoding $false))
"Wrote $($lines.Count) recipes to ClassicRecipes.lua"
