# Builds ClassicItems.lua: names of tradeable original Classic items (consumables,
# trade goods, recipes, bags, gems, ammo, and gear that binds when equipped), so
# shopping lists can find items the game hasn't loaded yet (flasks above the beta's
# level cap), and the Classic recipe for each crafted one (Craft on a shopping list).
# Source (MIT licence): wow-classic-items by nexus-devs
#   https://github.com/nexus-devs/wow-classic-items
# Run from the repo root:  powershell -File tools\build-item-names.ps1

$ErrorActionPreference = "Stop"
$tmp = Join-Path $env:TEMP "fl-classic-data"
New-Item -ItemType Directory -Force $tmp | Out-Null
$p = Join-Path $tmp "items.json"
if (-not (Test-Path $p)) {
  Invoke-WebRequest "https://raw.githubusercontent.com/nexus-devs/wow-classic-items/master/data/json/data.json" -OutFile $p
}
$items = Get-Content $p -Raw -Encoding UTF8 | ConvertFrom-Json
$inv = [Globalization.CultureInfo]::InvariantCulture
function Q([string]$s) { '"' + ($s -replace '\\', '\\' -replace '"', '\"') + '"' }
function Num($n) { ([double]$n).ToString($inv) }

# Every original Classic item (later expansions start around 24000; owner, October 2:
# "as much of the database as possible, not just what's in the beta"). Items that bind
# when picked up, and quest items, are listed in CLASSIC_BOUND so suggestions can put
# the ones you can buy first.
$byId = @{}
foreach ($it in $items) { $byId[[int]$it.itemId] = $it }
$keep = @{}
$bound = New-Object System.Collections.Generic.List[int]
foreach ($it in $items) {
  $id = [int]$it.itemId
  if ($id -gt 24000 -or $it.class -eq 'Glyph' -or $it.class -eq 'Money') { continue }
  $keep[$id] = $true
  $labels = @($it.tooltip | ForEach-Object { $_.label })
  if ($it.class -eq 'Quest' -or $labels -contains 'Binds when picked up' -or $labels -contains 'Quest Item') { $bound.Add($id) }
}

# Recipes for kept items, and their materials' names too.
$crafts = New-Object System.Text.StringBuilder
$nCrafts = 0
foreach ($id in ($keep.Keys | Sort-Object)) {
  $it = $byId[$id]
  $c = @($it.createdBy) | Where-Object { $_ -and $_.reagents } | Select-Object -First 1
  if (-not $c) { continue }
  $amt = @($c.amount)
  $oq = if ($amt.Count -ge 2) { ([double]$amt[0] + [double]$amt[1]) / 2 } elseif ($amt.Count -eq 1) { [double]$amt[0] } else { 1 }
  $mats = @()
  foreach ($r in $c.reagents) {
    $mats += "$([int]$r.itemId), $([int]$r.amount)"
    if ($byId[[int]$r.itemId]) { $keep[[int]$r.itemId] = $true }
  }
  [void]$crafts.AppendLine("  [$id] = { $(Num $oq), $(Q $c.category), $([int]$c.requiredSkill), { $($mats -join ', ') } },")
  $nCrafts++
}

$names = New-Object System.Text.StringBuilder
foreach ($id in ($keep.Keys | Sort-Object)) {
  $n = $byId[$id].name -replace '&apos;', "'"
  [void]$names.AppendLine("  [$id] = $(Q $n),")
}

$out = @"
local _, ns = ...

-- Original Classic item names and recipes, for shopping lists: finding items the game
-- hasn't loaded yet, and Craft for items none of your characters has the recipe for.
-- Generated by tools/build-item-names.ps1 from wow-classic-items (nexus-devs, MIT
-- licence). Don't edit by hand; rerun the script. Forever may have changed some.
--
-- CLASSIC_ITEMS[itemID] = name
-- CLASSIC_CRAFTS[itemID] = { made per craft, profession, skill, { material, count, material, count, ... } }
-- CLASSIC_BOUND = "id,id,..." items that bind when picked up, and quest items (can't be bought)
ns.CLASSIC_ITEMS = {
$($names.ToString())}

ns.CLASSIC_CRAFTS = {
$($crafts.ToString())}

ns.CLASSIC_BOUND = "$(($bound | Sort-Object) -join ',')"
"@
[IO.File]::WriteAllText((Join-Path (Get-Location) "ClassicItems.lua"), $out, (New-Object Text.UTF8Encoding $false))
"ClassicItems.lua: $($keep.Count) names ($($bound.Count) bound), $nCrafts recipes."
